AllCops:
  Exclude:
    - '.git/**/*'
    - '.vscode/**/*'
    - '.yarn/**/*'
    - 'config/routes.rb'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'sql/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
Layout/LineLength:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/HashLikeCase:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/TrailingCommaInArguments:
  Enabled: false
