default: &default
  adapter: postgresql
  host: localhost
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: postgres
  password: postgres
  database: kc_tennis_development
  pool: 5
  timeout: 5000

test:
  <<: *default
  username: postgres
  password: postgres
  database: kc_tennis_test

staging:
  primary: &primary_staging
    <<: *default
    url:  <%= ENV["DATABASE_URL"] %>
    pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
  cache:
    <<: *primary_staging
    url:  <%= ENV["DATABASE_URL"] %>
    migrations_paths: db/cache_migrate
  cable:
    <<: *primary_staging
    url:  <%= ENV["DATABASE_URL"] %>
    migrations_paths: db/cable_migrate

production:
  primary: &primary_production
    <<: *default
    url:  <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *primary_production
    url:  <%= ENV["DATABASE_URL"] %>
    migrations_paths: db/cache_migrate
  cable:
    <<: *primary_production
    url:  <%= ENV["DATABASE_URL"] %>
    migrations_paths: db/cable_migrate
