default: &default
  adapter: postgresql
  host: localhost
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: postgres
  password: postgres
  database: kc_tennis_development
  pool: 5
  timeout: 5000

test:
  <<: *default
  username: postgres
  password: postgres
  database: kc_tennis_test

staging:
  primary:
    <<: *default
    url:  <%= ENV["DATABASE_URL"] %>
    pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>

production:
  primary:
    <<: *default
    url:  <%= ENV["DATABASE_URL"] %>
    pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
