name: Continuous Integration

on: [push]

jobs:
  test:
    name: Run RSpec Tests
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
          
      - name: Read .tool-versions
        uses: marocchino/tool-versions-action@v1
        id: versions

      - name: Install ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ steps.versions.outputs.ruby }}

      - name: Install ruby gems
        run: bundle install

      - name: Scan for common Rails security vulnerabilities using static analysis
        run: bin/brakeman --no-pager

      - name: Install node
        uses: actions/setup-node@v4
        with:
          cache: "yarn"
          node-version: ${{ steps.versions.outputs.nodejs }}

      - name: Install node packages
        run: yarn install

      - name: Setup database
        run: bin/rails db:create db:schema:load

      - name: Build assets
        run: |
          yarn install --immutable
          mkdir -p app/assets/builds
          yarn build
          yarn dlx sass ./app/assets/stylesheets/admin.scss:./app/assets/builds/admin.css ./app/assets/stylesheets/public.scss:./app/assets/builds/public.css --no-source-map --style=compressed --load-path=/home/runner/work/kc-tennis/kc-tennis/node_modules

      - name: Run tests
        run: bundle exec rspec --format RSpec::Github::Formatter --format progress
